[package]
name = "tokocepat"
version = "0.2.5"
description = "Tokocepat - kasir cepat"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.3", features = [] }
tauri-plugin-log = "2"
serialport = "4.8.1"
json-patch = "0.3"
tauri-plugin-store = "2.4.2"
tauri-plugin-dialog = "2.6.0"
uuid = "1.20.0"
tokio = { version = "1", features = ["full"] }
firelite = { git = "https://github.com/rizaptk/firelite", branch = "main" , version = "0.5.30", features = ["tauri-gateway", "tokio"] }
machine-uid = "0.3"
rusb = "0.9"
tauri-plugin-fs = "2"
